class locator_resources():
    settings_button_xpath = "//button[@type='button']//div[@class='svg-icon ']//*[local-name()='svg']"
    login_button_xpath = "//body/div[@id='root']/main[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[3]/button[1]"
    logout_button_css = "button:nth-child(2) p:nth-child(1)"
    signup_button_xpath = "//header/div[1]/a[1]/button[1]"
    home_logo_xpath = "//h1[contains(text(),'Home')]"
    invalid_login_error_xpath = "/html[1]/body[1]/div[1]/main[1]/div[2]/div[1]/div[1]/div[1]/form[1]/span[1]"
    projects_link_xpath = "//button[contains(text(),'Projects')]"
    side_nav_layout_button_xpath = "//div[contains(@class,'side-nav-layout__expand-button__container')]//div[2]"
    logged_in_user_css = "div[class='side-nav__account-controls__username'] p"
    projects_link_xpath = "//button[contains(text(),'Projects')]"
    projects_title_xpath = "//h1[normalize-space()='Projects']"
    new_project_button_xpath = "//button[@class='button button--accent button-icon']"
    new_project_dialog_box_xpath = "div[role='dialog']"
    new_project_dialog_box_header_xpath = "//h3[normalize-space()='New Project']"
    new_project_field_xpath = "input-field-name"
    project_name_textarea_xpath = "textarea-field-nameTextArea"
    project_button_css = "button[class='button button--accent']"
    save_project_list_css = ".saved-project__list"
    project_header_xpath = "//button[contains(text(),'Projects')]"
    project_list_placeholder_search_css = "input[placeholder='Search...']"
    saved_projects_list_css = ".ConfigurationListHeadWrapper.saved-project"
    saved_projects_headline_css = ".saved-project__headline"
    saved_projects_cog_css = ".saved-project__cog"
    project_description_css = ".innerWrapper__description"
    saved_projects_headline_name_css = ".saved-project__headline__name__text"
    saved_projects_empty_list_css = ".saved-config--empty-list"
    edit_projects_list_css = "input[placeholder='Search...']"
    edit_projects_icon_xpath = "//i[@class='button__icon icon--cog']//div[@class='svg-icon ']//*[local-name()='svg']"
    rename_projects_button_xpath = "//p[contains(text(),'Rename')]"
    delete_projects_button_xpath = "//p[contains(text(),'Delete')]"
    projects_search_css = "input[placeholder='Search...']"
    save_project_button_css = ".saved-project__headline__name__text"
    new_simulation_button_xpath = "//button[@class='button button--accent button-icon saved-project__button--new-simulation']"
    simulation_settings_form_xpath = "//div[@class='settings-form']"
    simulation_name_css = "#input-field-name"
    simulation_description_css = "#textarea-field-description"
    simulation_market_count_css = "#input-field-marketCount"
    simulation_tickLengthSeconds_css = "#input-field-tickLengthSeconds"
    simulation_slotLengthRealtimeSeconds_css = "#input-field-slotLengthRealtimeSeconds"
    new_simulation_text_xpath = "//h1[contains(text(),'New Simulation')]"
    submit_new_simulation_xpath = ".button.button--accent.button-icon.settings-form__submit"
    new_modelling_header_text_xpath = "//h1[contains(text(),'Modelling')]"
    simulation_listing_main_content_css = ".saved-config__main-content"
    settings_icon_css = "//body/div[@id='root']/div[1]/div[2]/div[2]/div[1]/div[1]/section[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]"
    modelling_icon_css = "//body/div[@id='root']/div[1]/div[2]/div[2]/div[1]/div[1]/section[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/button[1]"
    simulation_listing_date_css = ".saved-config--pct-width__date"
    button_icon_icon_settings_dots_xpath = "//i[@class='button__icon icon--settings_dots']//div[@class='svg-icon ']//*[local-name()='svg']"
    button_icon_icon_modelling_dots_xpath = "//i[@class='button__icon icon--modelling']//div[@class='svg-icon ']//*[local-name()='svg']"
    button_new_modelling_list_xpath = "//body/div[@id='root']/div[1]/div[2]/div[2]/div[1]/div[1]/section[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[3]/button[1]"
    setting_button_new_modelling_list_xpath = "//body/div[@id='root']/div[1]/div[2]/div[2]/div[1]/div[1]/section[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[4]/div[1]/button[1]"
    simulation_listing_content_by_search_xpath = "//div[contains(@class,'ProjectsPage')]//div[1]//div[1]//div[1]//span[1]//div[2]"
    search_project_by_xpath = "//header/div[2]/input[1]"
    setting_button_by_xpath = "//button[@class='button button--light-blue button-icon button--icon-only']"
    delete_button_by_xpath = "//p[normalize-space()='Delete']"
    confirm_delete_button_by_xpath = "//body/div[7]/div[1]/div[1]/div[2]/div[1]/button[2]/span[1]"