# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pwd
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install Google Chrome # Using shell script to install Google Chrome
      run: |
       chmod +x ./scripts/InstallChrome.sh
        ./scripts/InstallChrome.sh
    - name: Test with behave
      run: |
        behave -f html -o reports/behave-report.html features
        
    - name: Allure report simple
    # You may pin to the exact commit or the version.
    # uses: esemi/action-allure-report@18e19222c45717d9c540260f4c2cd069f567fa11
      uses: esemi/action-allure-report@v0.2.0
      with:
      # Allure test result data dir
       results-dir: allure-results
      # Allure report target dir
       report-dir: allure-report
    - name: HTML Preview
    # You may pin to the exact commit or the version.
    # uses: pavi2410/html-preview-action@9420cd81fbbe0035f59a39536ea5a0443daffa37
      uses: pavi2410/html-preview-action@v2
      with:
      # The HTML file you want to preview, relative to the root of the repo
       html_file: ./allure-report/index.html
